alias: null
batch_size: 32
decoder_hidden_layers: 0
decoder_hidden_size: 0
drop_last_loader: false
early_stop_patience_steps: -1
exclude_insample_y: false
futr_exog_list: null
h: 33
hist_exog_list: null
inference_windows_batch_size: -1
input_size: 66
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.DistributionLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _base_distribution: !!python/name:torch.distributions.studentT.StudentT ''
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDQAAADIwOTM2MDQ1MDY3NTJxAlgDAAAAY3B1cQNLBU50cQRRLoACXXEAWA0AAAAyMDkz
              NjA0NTA2NzUycQFhLgUAAAAAAAAAAAAAP83MTD3NzMw9ZmZmPzMzcz8=
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  distribution: StudentT
  distribution_kwargs: {}
  domain_map: !!python/name:neuralforecast.losses.pytorch.student_domain_map ''
  is_distribution_output: true
  num_samples: 1000
  output_names:
  - ''
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADgAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADgAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAAwAAAA
  outputsize_multiplier: 3
  param_names:
  - -df
  - -loc
  - -scale
  return_params: false
  scale_decouple: !!python/name:neuralforecast.losses.pytorch.student_scale_decouple ''
  training: true
lstm_dropout: 0.1
lstm_hidden_size: 128
lstm_n_layers: 2
max_steps: 1000
num_lr_decays: 3
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
random_seed: 1
scaler_type: identity
start_padding_enabled: false
stat_exog_list: null
step_size: 1
trajectory_samples: 100
val_check_steps: 100
valid_batch_size: null
valid_loss: !!python/object:neuralforecast.losses.pytorch.MQLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDQAAADIwOTM2MDQ1MDczMTJxAlgDAAAAY3B1cQNLBU50cQRRLoACXXEAWA0AAAAyMDkz
              NjA0NTA3MzEycQFhLgUAAAAAAAAAAAAAPwAAAD4AAIA+AABAPwAAYD8=
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADcAAAA1AAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADUAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADUAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADcAAAA1AAAA
  outputsize_multiplier: 5
  training: true
windows_batch_size: 1024
